<?php

namespace App\Filament\Resources\Applications\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Tabs\Tab;
use Filament\Schemas\Schema;

class ApplicationInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('application-info')
                    ->columnSpanFull()
                    ->tabs([
                        Tab::make('application_info')
                            ->label(__('admin.application.application_info'))
                            ->columns(3)
                            ->schema([
                                TextEntry::make('ref_no')
                                    ->label(__('admin.application.ref_no'))
                                    ->placeholder('-'),
                                TextEntry::make('season.name')
                                    ->label(__('admin.application.season'))
                                    ->placeholder('-'),
                                TextEntry::make('program.name')
                                    ->label(__('admin.application.program'))
                                    ->placeholder('-'),
                                TextEntry::make('branch.name')
                                    ->label(__('admin.application.branch'))
                                    ->placeholder('-'),
                                TextEntry::make('status')
                                    ->label(__('admin.application.status'))
                                    ->badge()
                                    ->placeholder('-'),
                                TextEntry::make('created_at')
                                    ->label(__('admin.application.created_at'))
                                    ->dateTime()
                                    ->placeholder('-'),
                            ]),
                        Tab::make('student_info')
                            ->label(__('admin.application.student_info'))
                            ->columns(3)
                            ->schema([
                                TextEntry::make('student_name')
                                    ->label(__('admin.student.name'))
                                    ->placeholder('-'),
                                TextEntry::make('student_gender')
                                    ->label(__('admin.student.gender'))
                                    ->badge(),
                                TextEntry::make('student_birth_date')
                                    ->label(__('admin.student.birth_date'))
                                    ->date()
                                    ->placeholder('-'),
                                TextEntry::make('student_civil_number')
                                    ->label(__('admin.student.civil_number'))
                                    ->placeholder('-'),
                                TextEntry::make('student_state')
                                    ->label(__('admin.student.state'))
                                    ->placeholder('-'),
                                TextEntry::make('student_governorate')
                                    ->label(__('admin.student.governorate'))
                                    ->placeholder('-'),
                                TextEntry::make('student_village')
                                    ->label(__('admin.student.village'))
                                    ->placeholder('-'),
                                TextEntry::make('student_house_number')
                                    ->label(__('admin.student.house_number'))
                                    ->placeholder('-'),
                                TextEntry::make('student_parents_social_status')
                                    ->label(__('admin.student.parents_social_status'))
                                    ->placeholder('-'),
                                TextEntry::make('relationship_with_guardian')
                                    ->label(__('admin.student.relationship_with_guardian'))
                                    ->placeholder('-'),
                                IconEntry::make('is_transfer_student')
                                    ->label(__('admin.application.is_transfer_student'))
                                    ->boolean(),
                            ]),
                        Tab::make('father_info')
                            ->label(__('admin.application.father_data'))
                            ->columns(3)
                            ->schema([
                                TextEntry::make('father_name')
                                    ->label(__('admin.application.father_name'))
                                    ->placeholder('-'),
                                TextEntry::make('father_phone')
                                    ->label(__('admin.application.father_phone'))
                                    ->placeholder('-'),
                                TextEntry::make('father_email')
                                    ->label(__('admin.application.father_email'))
                                    ->placeholder('-'),
                                TextEntry::make('father_id_number')
                                    ->label(__('admin.application.father_id_number'))
                                    ->placeholder('-'),
                                TextEntry::make('father_occupation')
                                    ->label(__('admin.application.father_occupation'))
                                    ->placeholder('-'),
                                TextEntry::make('father_work_address')
                                    ->label(__('admin.application.father_work_address'))
                                    ->placeholder('-'),
                                TextEntry::make('father_work_phone')
                                    ->label(__('admin.application.father_work_phone'))
                                    ->placeholder('-'),
                                TextEntry::make('father_is_guardian')
                                    ->label(__('admin.application.father_is_guardian'))
                                    ->placeholder('-'),
                            ]),
                        Tab::make('mother_data')
                            ->label(__('admin.application.mother_data'))
                            ->columns(3)
                            ->schema([
                                TextEntry::make('mother_name')
                                    ->label(__('admin.application.mother_name'))
                                    ->placeholder('-'),
                                TextEntry::make('mother_phone')
                                    ->label(__('admin.application.mother_phone'))
                                    ->placeholder('-'),
                                TextEntry::make('mother_email')
                                    ->label(__('admin.application.mother_email'))
                                    ->placeholder('-'),
                                TextEntry::make('mother_id_number')
                                    ->label(__('admin.application.mother_id_number'))
                                    ->placeholder('-'),
                                TextEntry::make('mother_occupation')
                                    ->label(__('admin.application.mother_occupation'))
                                    ->placeholder('-'),
                                TextEntry::make('mother_work_address')
                                    ->label(__('admin.application.mother_work_address'))
                                    ->placeholder('-'),
                                TextEntry::make('mother_work_phone')
                                    ->label(__('admin.application.mother_work_phone'))
                                    ->placeholder('-'),
                                TextEntry::make('mother_is_guardian')
                                    ->label(__('admin.application.mother_is_guardian'))
                                    ->placeholder('-'),
                            ]),
                        Tab::make('relative_data')
                            ->label(__('admin.application.relative_data'))
                            ->columns(3)
                            ->schema([
                                TextEntry::make('relative_name')
                                    ->label(__('admin.application.relative_name'))
                                    ->placeholder('-'),
                                TextEntry::make('relative_phone')
                                    ->label(__('admin.application.relative_phone'))
                                    ->placeholder('-'),
                                TextEntry::make('relative_email')
                                    ->label(__('admin.application.relative_email'))
                                    ->placeholder('-'),
                                TextEntry::make('relative_id_number')
                                    ->label(__('admin.application.relative_id_number'))
                                    ->placeholder('-'),
                                TextEntry::make('relative_occupation')
                                    ->label(__('admin.application.relative_occupation'))
                                    ->placeholder('-'),
                                TextEntry::make('relative_work_address')
                                    ->label(__('admin.application.relative_work_address'))
                                    ->placeholder('-'),
                                TextEntry::make('relative_work_phone')
                                    ->label(__('admin.application.relative_work_phone'))
                                    ->placeholder('-'),
                            ]),
                    ]),
            ]);
    }
}
